Iter19
rebus2015/praktikum-devops pull request #19
Opened 2023-09-15 22:17 UTC by rebus2015

2023-09-18 14:18 UTC, s-shpak requested changes
Пожалуйста, именуй ветки согласно последнему инкременту, над которым ты работаешь (в этом случае верное название - `iter20`)

2023-09-18 14:18 UTC, s-shpak commented on cmd/agent/main.go
> +			syscall.Exit(0)
Почему ты сделал это изменение ?

2023-09-18 14:18 UTC, s-shpak commented on main
Бинарные файлы не надо пушить в репозиторий

2023-09-18 14:18 UTC, s-shpak commented on staticlint
Бинарные файлы не надо пушить в репозиторий

2023-09-18 14:18 UTC, s-shpak commented on cmd/staticlint/analyzers/custom/analyzer.go
> +							if ok && fmt.Sprintf("%s.%s", fun.X, fun.Sel.Name) == "os.Exit" {
Не стоит вызывать `fmt.Sprintf` здесь - это дорого. Проверь просто `fun.X` и `fun.Sel.Name`

2023-09-18 14:18 UTC, s-shpak commented on internal/storage/dbstorage/postgresqlStorage.go
Файлы в Go называбтся либо snake-case'ом, либо kebab-case'ом

2023-09-18 14:18 UTC, s-shpak commented on internal/storage/dbstorage/postgresqlStorage.go
> +	db.SetMaxOpenConns(1000)
Это очень много, дефолтный деплой на среднем сервере может не выдержать 100 соединений. Я бы советовал выбрать значение меньше 100

2023-09-18 14:18 UTC, s-shpak commented on internal/storage/dbstorage/postgresqlStorage_test.go
> +	// "sync"
Комментарии надо удалять

2023-09-18 14:18 UTC, s-shpak commented on internal/storage/dbstorage/postgresqlStorage_test.go
> +// func TestPostgreSQLStorage_Save(t *testing.T) {
Аналогично

2023-09-18 14:18 UTC, s-shpak commented on internal/storage/filestorage/filestorage_test.go
> +				StoreFile: "badStorage.txt",
Используй для этого https://pkg.go.dev/os#CreateTemp и https://pkg.go.dev/testing#T.TempDir

2023-09-20 18:26 UTC, rebus2015 commented on cmd/agent/main.go
> +			syscall.Exit(0)
самописный linter не должен пропускать os.exit, в задании написано, что код должен проходить его проверку

2023-09-24 10:31 UTC, merged